### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Grantelbart4** [OpenRA/ra2#213]
Hello, I downloaded the the openra-tibsunra2-master.zip, extracted it, installed it and i was able to play tiberian sun without any problems. But then i tried to play RA2 and moved the 4 required mix files into the required folder, but whenever I load the ra2 mod I get a fatal error. A guy on youtube even recorded the same error I got. https://www.youtube.com/watch?v=gKrE2_FE-v8
Even in the debug file i get the same. Does anyone know what I did wrong?

**Comment by abcdefg30** [comment]
It seems like the "tool" you were downloading contains an outdated version. Without the contents of  `exception.log` we can't help more.

Anyway, you can try following https://github.com/OpenRA/ra2/wiki/Step-by-Step , although, we're currently working on a refactor of the mod'S structure which should make installation easier (see #208).

**Comment by Grantelbart4** [comment]
Thanks for your response. I followed the guide till step 4 where I got this error:
![fehler](https://cloud.githubusercontent.com/assets/19558564/15519811/20e63ac0-21b8-11e6-9fde-552afe66b7db.PNG)
I am sorry that it is in german. It says:
Test-Path : The argument can't be bount to the parameter "Path" because it is NULL.
At C:\Users\Fulgur\Documents\Openra\mods\ra2\make.ps1:71 Characters:17

**Comment by GraionDilach** [comment]
make dependencies C:\path\to\a\checked\out\and\compiled\OpenRA\bleed

You need to supply a path for that parameter.

**Comment by GraionDilach** [comment]
On a second thought, this might fail atm, due to upstream's .NET version bump.

**Comment by Grantelbart4** [comment]
![kack](https://cloud.githubusercontent.com/assets/19558564/15553622/b751cb34-2274-11e6-984f-f26ab509cac2.PNG)
Thanks for the response, but now I get this. I tried to create the missing files by executing the make.cmd in the bleed folder, but I only get a list of errors.

**Comment by GraionDilach** [comment]
You need to run make dependencies there first, then make all. The list of errors are coming from that.

**Comment by Grantelbart4** [comment]
It worked now, but when I launch OpenRa.Game.exe the game crashes while loading the normal ra1 mod. The debug.log only says:
"Failed to initialize hardware cursors. Falling back to software cursors.
Error was: Failed to create hardware cursor `guard-minimap` - Failed to create cursor: CreateIconIndirect(): Falscher Parameter.

Found 35 domains for movement class 699 on map Desert Shellmap.
Found 3 domains for movement class 4096 on map Desert Shellmap."

**Comment by Grantelbart4** [comment]
I was able to fix it myself o.0
I just downloaded bleed, put the mix files into the ra2 mods folder and loaded the mod.

**Comment by GraionDilach** [comment]
Hardware cursors failing are kinda common lately, but the cause is still under investigation.

I guess this issue is resolved now.

**Comment by Grantelbart4** [comment]
Not anymore :/ I still get it when I have an allied airfield for a while, move a plain or have one for a while.

**Comment by GraionDilach** [comment]
Open a new issue please and c'n'p exception.log atleast.

**Comment by Grantelbart4** [comment]
Yes sir

**Comment by Walkman100** [comment]
```
Test-Path : The argument can't be bount to the parameter "Path" because it is NULL.
At C:\Users\Fulgur\Documents\Openra\mods\ra2\make.ps1:71 Characters:17
```
oh damn, seems like it doesn't execute the else part of my if condition:
```posh
	if ($args.Length -eq 1)
	{
		$OpenRADir = Read-Host "Enter the path to your OpenRA install"
	}
	else
	{
		$OpenRADir = $command[1]
	}
```
this was merged in #211
